name: Build AsciiDoc to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Asciidoctor
        run: sudo apt update && sudo apt install -y asciidoctor

      - name: Build AsciiDoc files (with styling)
        run: |
          mkdir -p docs
          asciidoctor -a stylesheet=https://cdnjs.cloudflare.com/ajax/libs/asciidoctor.js/2.2.6/css/asciidoctor.min.css -a linkcss -D docs *.adoc

      - name: Commit built site
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git commit -m "Generate styled site from AsciiDoc" || echo "No changes to commit"
          git push
